server:
  port: 8080
  servlet:
    context-path: /springboot
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  datasource:
      data-source: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/springboot
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true